on:
  push:
    branches:
      - release
jobs:
  publish:
    name: Publish to releases
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.38.0
        with:
          ruby-version: 2.7
      - name: Setup Homebrew
        run: |
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          sudo xcodebuild -license accept
      - name: Setup Wine and Mono
        run: |
          brew cask install xquartz
          brew cask install wine-stable
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run publish
