on:
  push:
    branches:
      - release
jobs:
  publish:
    name: Publish to releases
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install and publish
        run: |
          npm install
          GITHUB_TOKEN='${{secrets.GITHUB_TOKEN}}' npm run publish
